### ISSUE TITLE
支持 `::` 的用户名：域工作账号机制 

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#122]
# 需求的动机

如果某公司创建一个域 `abc` 那么，他希望他的员工也加入到这个域，并且大家的 `HOME` 都是 `/home/abc` 这样比较容易共享数据。 当然通过设置环境变量 `HOME` 可以很容易的解决这个问题，但是:

- 权限界面，不能提升出这个域所有的用户
- 一个员工如果绑定了手机，那么他就不能在 Walnut 上用手机创建自己的私人账户

# 解决办法

我们给出一个`域工作账号`的概念，即，你的账号如果是 `abc::xiaobai` 那么就被认为是域工作账号，这样的账号:

- 创建时，不会创建自己的主目录，也不会创建自己的主组
- 自己的主组就是 `abc`，自己的主目录就是 `/home/abc`
- 其手机号和邮箱等可登陆信息前面都会增加 `abc::` 作为前缀

这样的账号我们称为 `域工作账号`，它享有 walnut 标准账号的一切好处，且没有独立主目录等诸多烦恼。非常适合一个组织创建自己的工作账号

# TODOs

- [ ] walnut 显示登录界面的时候，增加 `default_work` 选项。 如果 domain 有映射则提交时增加前缀
- [ ] 自定义注册界面也是同理
- [ ] 用户服务，对于域工作账号的创建，将不创建主目录和组目录，直接在域的组里加一个了事
- [ ] 工作账号登录一定会增加一个环境变量 `WORK_GRP=abc`
- [ ] 权限界面如果发现有 `WORK_GRP`  则提示用户的时候，一定会加上前缀
