### ISSUE TITLE
菊花版精编

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#284]
这里列出了菊花版要达成的目标

# 可以切实的开展业务

- [ ] 可以支持代理商机制
- [x] 代金券机制
- [ ] 磁盘和流量监控
- [ ] 数据备份支持
- [ ] #248 支持一个测试域名

# 有效的帮用户克服恐惧

- [ ] 建立一个帮助体系
    + ZUI 支持的更华丽的 balloon
    + 建立教程文档，分作多国语言存放
    + 建立教程视频，分作多国语言存放

# 更好的用户体验

- [x] 完善的 thing 编辑界面 #285
- [ ] 皮肤自定义机制
- [ ] 一个完整的默认皮肤
- [ ] 主题市场，这样新建站点的时候可以选择主题
- [ ] 素材市场，完善图片选择框
- [ ] #135 提供 undo/redo/copy/cut/paste
- [ ] 支持自动保存或者文件修改后提示

# 更高的运行效率

- [ ]  #281   RegAPI 支持路径参数
- [ ]  #276  缩略图请求 /o/thumbnail 也应该支持 304
- [ ]  #258 httpapi 的 `http-dynamic-header` 应该更加智能

# 没有重大错误

- [ ] #271  hMaker 增加 html 插件，写这个重新加载页面就出错了
- [ ] #279 !! GuestModule 可以读到任何文件
- [x] #219 若指定域名的404.html找不到,会循环404错误
- [ ] #126 firefox 上的 PageUI 加载不出来
