### ISSUE TITLE
hMaker: 统一修改皮肤机制的任务总表

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#304]
# 机制修改:

- [x] 皮肤机制汇总文档
    - [x] [hMaker 总体设计](/zozoh/walnut/blob/master/doc/ext/hmaker/hm_overview.md)
    - [x] [hMaker 皮肤机制](/zozoh/walnut/blob/master/doc/ext/hmaker/hm_skin.md)
        + 还需要描述如何编译 lessc
        + 引入到站点，不直接使用 css 文件，必须要通过 lessc
    - [x] [hMaker 模板机制](/zozoh/walnut/blob/master/doc/ext/hmaker/hm_template.md)
    - [x] [hMaker 网站原型](/zozoh/walnut/blob/master/doc/ext/hmaker/hm_prototype.md)
- [x] 皮肤相关修改
    - [x] 将变量文件改名为 `_skin_var.less`
    - [x] 站点配置界面支持编辑 `_skin_var.less` #397
    - [x] 提供 `hmaker read`，动态读取生成的 skin.css #270
- [x] 模板相关的修改
    - #307
- [x] 编辑器修改
    - [x] area 提供默认的上下左右等排布方式 #308
    - [x] 提供默认的 html.font-size 修改功能，不需要每个皮肤都指定 #311
- [x] markdown 扩展支持 #315
- [x] 默认皮肤 zozoh/site0#90
