### ISSUE TITLE
ui: 提供 layout 控件

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#468]
为了让复杂界面编写更加容易，提供了 `ui/layout` 控件：

- 作为所有子控件的消息  bus
- 通过 xml 指定更复杂和有表现力的布局

# Tasks

- [x] [定义 layout.xml](https://github.com/zozoh/walnut/blob/master/doc/ui/layout/layout_xml.md)
- [x] [定义 layout.json](https://github.com/zozoh/walnut/blob/master/doc/ui/layout/layout_json.md)
- [x] [定义 layout.dom](https://github.com/zozoh/walnut/blob/master/doc/ui/layout/layout_dom.md)
- [x] [定义 layout.js](https://github.com/zozoh/walnut/blob/master/doc/ui/layout/layout.md)
- [x] [定义 layout 消息事件](https://github.com/zozoh/walnut/blob/master/doc/ui/layout/layout_event.md)
- [x] 实现·测试脚手架
- [x] 实现·layout语法的解析和渲染
- [x] 实现·计算 resize
- [x] 实现·布局·cols/rows : 展开/收起
- [x] 实现·布局·tabs : 切换
- [x] 实现·布局·box ：自动计算/隐藏
- [x] 实现·菜单·事件消息触发的配置
- [x] 实现·子控件的加载
- [x] 测试·列表/标签/box 的联动
